    drop table car if exists;

    drop table driver if exists;

    create table car (
        car_id bigint generated by default as identity,
        total_seat varchar(255) not null,
        car_type varchar(255) not null,
        purchase_date timestamp,
        license_no varchar(255) not null,
        rating varchar(255),
        driver_id bigint,
        manufacturer varchar(255),
        primary key (car_id));

        alter table car
        add constraint license_no unique (license_no);

    create table driver (
        driver_id bigint generated by default as identity,
        coordinate binary(255),
        date_coordinate_updated timestamp,
        date_created timestamp not null,
        online_status varchar(255) not null,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (driver_id)
    );

       alter table driver
        add constraint uc_username unique (username);

